=== SciCoderG/leWebz/xmlschema/u11.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="abschlussarbeit">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zusammenfassung" type="xs:string"/>
				<xs:element name="abstract" type="xs:string"/>
				<xs:element name="einleitung" type="einleitungType"/>
				<xs:element name="arbeiten" type="arbeitenType"/>
				<xs:element name="grundlagen" type="xs:string"/>
				<xs:element name="konzept" type="xs:string"/>
				<xs:element name="realisierung" type="xs:string"/>
				<xs:element name="implementierung" type="xs:string"/>
				<xs:element name="beispiel" type="xs:string"/>
				<xs:element name="szenarien" type="xs:string"/>
				<xs:element name="ausblick" type="xs:string"/>
				<xs:element name="literatur" type="literaturType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="einleitungType">
		<xs:sequence>
			<xs:element name="motivation" type="xs:string"/>
			<xs:element name="ziele" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="arbeitenType">
		<xs:sequence>
			<xs:element name="arbeit" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="literaturType">
		<xs:sequence>
			<xs:element name="eintrag" type="eintragType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eintragType">
		<xs:attribute name="titel" type="xs:string" use="required"/>
		<xs:attribute name="autor" type="xs:string" use="required"/>
		<xs:attribute name="seite" type="xs:int" use="required"/>
		<xs:attribute name="verlag" type="xs:string" use="required"/>
		<xs:attribute name="jahr" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== SciCoderG/leWebz/xmlschema/u11Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="u11Style.xslt" ?>
<abschlussarbeit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="u11.xsd">
	<zusammenfassung>Zusammenfassung</zusammenfassung>
	<abstract>Abstract</abstract>
	<einleitung>
		<motivation>Motivation</motivation>
		<ziele>Ziele</ziele>
	</einleitung>
	<arbeiten>
		<arbeit>Arbeit 1</arbeit>
		<arbeit>Arbeit 2</arbeit>
		<arbeit>Arbeit 3</arbeit>
	</arbeiten>
	<grundlagen>Grundlagen</grundlagen>
	<konzept>Konzept</konzept>
	<realisierung>Realisierung</realisierung>
	<implementierung>Implementierung</implementierung>
	<beispiel>Beispiel</beispiel>
	<szenarien>Szenarien</szenarien>
	<ausblick>Ausblick</ausblick>
	<literatur>
		<eintrag titel="Titel 1" autor="Autor 1" seite="42" verlag="Verlag 1" jahr="2242"/>
		<eintrag titel="Titel 2" autor="Autor 2" seite="420" verlag="Verlag 2" jahr="2142"/>
		<eintrag titel="Titel 3" autor="Autor 3" seite="4200" verlag="Verlag 3" jahr="2042"/>
	</literatur>
</abschlussarbeit>
