=== SciCoderG/leWebz/Webtech3/src/uebung10/Hausarbeit.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT hausarbeit (zusammenfassung,abstract,einleitung,verwandteArbeiten,grundlagen,konzept,realisierung,implementierung,beispiel,anwendungsszenarien,ausblick,literaturverzeichnis)>
<!ELEMENT zusammenfassung (#PCDATA)>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT einleitung (#PCDATA)>
<!ELEMENT verwandteArbeiten (arbeit+)>
<!ELEMENT arbeit (#PCDATA)>
<!ELEMENT grundlagen (#PCDATA)>
<!ELEMENT konzept (#PCDATA)>
<!ELEMENT realisierung (#PCDATA)>
<!ELEMENT implementierung (#PCDATA)>
<!ELEMENT beispiel (#PCDATA)>
<!ELEMENT anwendungsszenarien (#PCDATA)>
<!ELEMENT ausblick (#PCDATA)>
<!ELEMENT literaturverzeichnis (eintrag+)>
<!ELEMENT eintrag  EMPTY>

<!ATTLIST eintrag

titel CDATA  #REQUIRED
autor CDATA #REQUIRED
seite CDATA #REQUIRED
verlag CDATA  #REQUIRED
jahr CDATA #REQUIRED
>

=== SciCoderG/leWebz/Webtech3/src/uebung10/hausarbeit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hausarbeit SYSTEM "D:\workspace\Webtech\src\uebung10\Hausarbeit.dtd">
<hausarbeit>
<zusammenfassung>
 Zusammenfassung der Hausarbeit</zusammenfassung>
<abstract> abstract</abstract>
<einleitung>Hier steht die Einleitung meiner Hausarbeit</einleitung>
<verwandteArbeiten>
<arbeit> Bsp. Arbeit </arbeit>
<arbeit>another Arbeit</arbeit>
<arbeit> example 3</arbeit>
</verwandteArbeiten>
<grundlagen>Grundlagen </grundlagen>
<konzept> Das Konzept der Arbeit</konzept>
<realisierung>blablaaaa</realisierung>
<implementierung>Imlementierung </implementierung>
<beispiel>ein Beispiel</beispiel>
<anwendungsszenarien>m√∂gliche Anwendungszenarien</anwendungsszenarien>
<ausblick>Ein Ausblick</ausblick>
<literaturverzeichnis>

<eintrag
 titel="titel der Quelle"
 autor="Autor der Quelle"
 verlag="Verlag der Quelle"
 seite="135"
 jahr="1998"
/>

<eintrag
 titel="Another Quelle"
 autor="Autor 2 Quelle"
 verlag="Verlag 2"
 seite="135"
 jahr="2015"
/>
</literaturverzeichnis>
</hausarbeit>
